# project
title: Xtend
version: 0.1.0
description: Frontend library
homepage:
license: CC Attribution 3.0 Unported
author: Riccardo Caroli <beaver82@gmail.com>

# settings
host: 127.0.0.1
port: 4000
source: src/docs/
destination: docs/
baseurl:
exclude:
  - "*.psd"
  - "*.less"

# collections
collections:
  docs:
    output: true
    permalink: "/:collection/:path/"
    links:
      github: "https://github.com/minimit/xtend-library"
      download: "https://github.com/minimit/xtend-library/releases/latest"
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: sidebar
