name: 'Setup'

runs:
  using: "composite"
  steps:
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: "${{ env.NODE }}"
    - name: Yarn Cache Path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Yarn Cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-v${{ env.NODE }}-yarn1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-v${{ env.NODE }}-yarn1-
    - name: Yarn
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --prefer-offline
