name: 'Build'

runs:
  using: "composite"
  steps:
    - name: Custom Build (jsx generation)
      run: yarn custom
    - name: Lint
      run: yarn lint --fix
    - name: Check unstaged
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    - name: Exit if unstaged
      if: steps.changes.outputs.changed == 1
      run: |
        echo "There are unstaged changes, use 'yarn generate' and commit changes"
        git status
        exit 1
    - name: Build
      run: yarn build
      env:
        CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
