name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.github_pages_github_token }}
          BRANCH: gh-pages
          FOLDER: public
          GIT_CONFIG_NAME: minimit
          GIT_CONFIG_EMAIL: beaver82@gmail.com
