name: Lint

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  NODE: 18.x

jobs:
  lint:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    # setup/action.yml composite
    - name: Node setup
      uses: actions/setup-node@v3
      with:
        node-version: "${{ env.NODE }}"
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Pnpm
      run: pnpm install --frozen-lockfile --prefer-offline
    # lint/action.yml composite
    - name: Lint
      run: pnpm lint
      env:
        SHELL: bash
