name: Release

on:
  workflow_run:
    workflows: ["Test"]
    branches:
      - master
      - beta
      - 1.0-stable
    types:
      - completed

env:
  NODE: 12.x

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/setup
    - name: Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/git
            @semantic-release/github
            @semantic-release/release-notes-generator
      env:
        GITHUB_TOKEN: ${{ secrets.semantic_release_github_token }}
        NPM_TOKEN: ${{ secrets.semantic_release_npm_token }}
  deploy:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta' }}
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - uses: ./.github/workflows/setup
    - uses: ./.github/workflows/build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.semantic_release_github_token }}
        BRANCH: gh-pages
        FOLDER: public
        GIT_CONFIG_NAME: minimit
        GIT_CONFIG_EMAIL: beaver82@gmail.com
