name: Release

on:
  workflow_run:
    workflows: ["Test"]
    branches:
      - master
      - beta
      - 1.0-stable
    types:
      - completed

env:
  NODE: 12.x

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: "${{ env.NODE }}"
    - name: Yarn Cache Path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Yarn Cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-v${{ env.NODE }}-yarn1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-v${{ env.NODE }}-yarn1-
    - name: Yarn
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --prefer-offline
    - name: Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/git
            @semantic-release/github
            @semantic-release/release-notes-generator
      env:
        GITHUB_TOKEN: ${{ secrets.semantic_release_github_token }}
        NPM_TOKEN: ${{ secrets.semantic_release_npm_token }}
  deploy:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta' }}
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: "${{ env.NODE }}"
    - name: Yarn Cache Path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Yarn Cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-v${{ env.NODE }}-yarn1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-v${{ env.NODE }}-yarn1-
    - name: Yarn
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --prefer-offline
    - name: Custom Build (jsx generation)
      run: yarn custom
    - name: Lint
      run: yarn lint --fix
    - name: Check unstaged
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    - name: Exit if unstaged
      if: steps.changes.outputs.changed == 1
      run: |
        echo "There are unstaged changes, use 'yarn generate' and commit changes"
        git status
        exit 1
    - name: Build
      run: yarn build
      env:
        CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.semantic_release_github_token }}
        BRANCH: gh-pages
        FOLDER: public
        GIT_CONFIG_NAME: minimit
        GIT_CONFIG_EMAIL: beaver82@gmail.com
