name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  NODE: 12.x

jobs:
  codeql:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  build:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: "${{ env.NODE }}"
    - name: Yarn
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
      env:
        CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
    - name: Lint
      run: yarn lint
